# see `man dnf.conf` for defaults and possible options

[main]
allow_vendor_change=False
assumeno=False
assumeyes=False
autocheck_running_kernel=True
best=False
cacheonly=False
check_config_file_age=True
clean_requirements_on_remove=True
color=always
countme=False
debug_solver=False
defaultyes=False
diskspacecheck=True
enablegroups=True
fastestmirror=True
gpgcheck=True
gpgkey_dns_verification=True
ignorearch=False
installonly_limit=2
keepcache=False
localpkg_gpgcheck=True
log_compress=True
log_rotate=1
max_parallel_downloads=10
metadata_expire=3600
metadata_timer_sync=3600
module_stream_switch=False
multilib_policy=best
persistence=auto
protect_running_kernel=True
proxy_auth_method=none
proxy_sslverify=True
repo_gpgcheck=True
retries=4
skip_if_unavailable=True
sslverify=True
sslverifystatus=True
strict=False
throttle=0
timeout=10
upgrade_group_objects_upgrade=True
zchunk=True
